### PR TITLE
Initial draft

### PR DESCRIPTION
**Pull request by mp911de**
Check it out for `versioneye:create` and `versioneye:json` and lets start a discussion so I can contribute `versioneye:update` and `versioneye:licenseCheck`

Build:

`sbt publish` for building/publishing and `sbt scripted` to run the tiny create-pom.json-testsuite :)

### CODE REVIEW

**Comment by reiz** [comment]
Awesome :-) 

`sbt publish` works fine. But `sbt versioneye:json` returns: 

```
[info] Loading project definition from /Users/reiz/workspace/versioneye/versioneye_sbt_plugin/project
[info] Set current project to sbt-versioneye-plugin (in build file:/Users/reiz/workspace/versioneye/versioneye_sbt_plugin/)
[error] Not a valid key: json (similar: version)
[error] versioneye:json
[error]
```

Or did I something wrong? The output for `sbt versioneye:create` is similar: 

```
[info] Loading project definition from /Users/reiz/workspace/versioneye/versioneye_sbt_plugin/project
[info] Set current project to sbt-versioneye-plugin (in build file:/Users/reiz/workspace/versioneye/versioneye_sbt_plugin/)
[error] Not a valid key: create (similar: aggregate, state, clean)
[error] versioneye:create
[error]
```

Not sure if I'm doing something wrong.

**Comment by mp911de** [comment]
You can't use the plugin in the plugin-project right now, because you would create a infinite recursion :) Create a sbt project where you reference the plugin (see ttps://www.dropbox.com/s/vys4e7wttt4qzw5/versioneye-test.zip?dl=0).

**Comment by reiz** [comment]
@mp911de  Awesome. It works! 

I just double checked the pom.json. Looks good to me. 
I deleted the versioneye.properties file and replaced the API Key with my own. After `sbt versioneye:create` it created a new properties file and the project was created in my user account. Everything like expected :+1:

**Comment by mp911de** [comment]
ping. Should fulfil the initial requirements

**Comment by reiz** [comment]
Awesome. I'm testing it :+1:

**Comment by reiz** [comment]
I just tested it and found a little bug. It seems that the pom.json is missing the artifactIds. I add this line to my build.sbt: 

```
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.1"
```

The pom.json contains this here: 

```
{"name":"org.apache.commons","version":"3.1","scope":"compile"}
```

The name contains the groupId, but not the artifactId. Correct would be this here: 

```
{"name":"org.apache.commons:commons-lang3","version":"3.1","scope":"compile"}
```

Otherwise it looks good :+1:

**Comment by mp911de** [comment]
You're right. VersionEye finds then the dependencies once the artifact name is right. Fixed it.

**Comment by reiz** [comment]
Awesome. It works :+1: 

Just one little thing. For the case of a license whitelist violation I'm getting an Exception with this message: 

```
[error] (versioneye:licenseCheck) java.lang.IllegalStateException: Some components violate the license whitelist! More details here: sbt.SettingKey$$anon$4@71a6f6f9/user/projects/55dc1a3e7a7c24000c03b008
```

I guess some string concatenation goes wrong, because `sbt.SettingKey$$anon$4@71a6f6f9` should be `https://www.versioneye.com`. 

But otherwise it really works like expected. Great Job :+1:

**Comment by reiz** [comment]
@mp911de I just merged it :-)

**Comment by mp911de** [comment]
You were too fast

**Comment by reiz** [comment]
@mp911de Sorry, I was too excited about this plugin :-)

**Pull request merged**
